// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SCICHRPortal.Repository;

#nullable disable

namespace SCICHRPortal.Repository.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260811140042_AddedProjectAndDevice")]
    partial class AddedProjectAndDevice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SCICHRPortal.Data.Entities.Announcement", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnnouncementId"));

                    b.Property<string>("AnnouncementForm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("AnnouncementId");

                    b.ToTable("Announcement");
                });

            modelBuilder.Entity("SCICHRPortal.Data.Entities.Audit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NewValues")
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryKey")
                        .HasColumnType("text");

                    b.Property<string>("RequestOrigin")
                        .HasColumnType("text");

                    b.Property<string>("SystemName")
                        .HasColumnType("text");

                    b.Property<string>("TableName")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("SCICHRPortal.Data.Entities.BiometricsLog", b =>
                {
                    b.Property<int>("BiometricsLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BiometricsLogId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("DeviceName")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("LogType")
                        .HasColumnType("text");

                    b.Property<string>("PersonnelId")
                        .HasColumnType("text");

                    b.Property<string>("ProjectName")
                        .HasColumnType("text");

                    b.Property<Guid?>("SZKDevicesId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<int?>("XCompany_BranchId")
                        .HasColumnType("integer");

                    b.HasKey("BiometricsLogId");

                    b.HasIndex("SZKDevicesId");

                    b.HasIndex("XCompany_BranchId");

                    b.ToTable("BiometricsLog");
                });

            modelBuilder.Entity("SCICHRPortal.Data.Entities.EmployeeAttendance", b =>
                {
                    b.Property<int>("EmployeeAttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployeeAttendanceId"));

                    b.Property<bool>("ApprovedHoliday")
                        .HasColumnType("boolean");

                    b.Property<bool>("ApprovedHolidayOT")
                        .HasColumnType("boolean");

                    b.Property<bool>("ApprovedOT")
                        .HasColumnType("boolean");

                    b.Property<bool>("ApprovedRestDay")
                        .HasColumnType("boolean");

                    b.Property<bool>("ApprovedRestDayOT")
                        .HasColumnType("boolean");

                    b.Property<bool>("ApprovedSPHoliday")
                        .HasColumnType("boolean");

                    b.Property<bool>("ApprovedSPHolidayOT")
                        .HasColumnType("boolean");

                    b.Property<int?>("Company_BranchId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFlexibleShift")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNoBreak")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNoShift")
                        .HasColumnType("boolean");

                    b.Property<double>("NDHours")
                        .HasColumnType("double precision");

                    b.Property<double>("OTHours")
                        .HasColumnType("double precision");

                    b.Property<double>("RegularHour")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("ShiftEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("ShiftHours")
                        .HasColumnType("double precision");

                    b.Property<double>("ShiftLate")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("ShiftStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("ShiftUndertime")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("TimeIn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TimeLogId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeOut")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("TotalLoggedHours")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("ZKDevicesId")
                        .HasColumnType("uuid");

                    b.HasKey("EmployeeAttendanceId");

                    b.HasIndex("Company_BranchId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TimeLogId");

                    b.HasIndex("ZKDevicesId");

                    b.ToTable("EmployeeAttendance");
                });

            modelBuilder.Entity("SCICHRPortal.Data.Entities.EmployeeShift", b =>
                {
                    b.Property<int>("AssignedShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AssignedShiftId"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<int?>("Company_Branch_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FridayShiftEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FridayShiftStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsFlexibleShift")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNoBreak")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNoShift")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("MondayShiftEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("MondayShiftStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("SZKDevicesId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SaturdayShiftEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("SaturdayShiftStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ShiftId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SundayShiftEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("SundayShiftStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ThursdayShiftEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ThursdayShiftStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("TuesdayShiftEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("TuesdayShiftStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("WednesdayShiftEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("WednesdayShiftStart")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("AssignedShiftId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SZKDevicesId");

                    b.HasIndex("ShiftId");

                    b.ToTable("EmployeeShift");
                });

            modelBuilder.Entity("SCICHRPortal.Data.Entities.EmployeeShiftDevice", b =>
                {
                    b.Property<int>("AssignedShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AssignedShiftId"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Devicename")
                        .HasColumnType("text");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FridayShiftEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FridayShiftStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsFlexibleShift")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNoBreak")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNoShift")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("MondayShiftEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("MondayShiftStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("SZKDevicesId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SaturdayShiftEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("SaturdayShiftStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ShiftId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SundayShiftEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("SundayShiftStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ThursdayShiftEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ThursdayShiftStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("TuesdayShiftEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("TuesdayShiftStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("WednesdayShiftEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("WednesdayShiftStart")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("AssignedShiftId");

                    b.HasIndex("BranchId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SZKDevicesId");

                    b.HasIndex("ShiftId");

                    b.ToTable("EmployeeShiftDevice");
                });

            modelBuilder.Entity("SCICHRPortal.Data.Entities.EmployeeTimeLog", b =>
                {
                    b.Property<int>("TimeLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TimeLogId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateIn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateOut")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("DeviceTimeIn")
                        .HasColumnType("text");

                    b.Property<string>("DeviceTimeOut")
                        .HasColumnType("text");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<bool>("IsFlexibleShift")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNoBreak")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNoShift")
                        .HasColumnType("boolean");

                    b.Property<string>("ProjecTimeIn")
                        .HasColumnType("text");

                    b.Property<string>("ProjectTimeOut")
                        .HasColumnType("text");

                    b.Property<Guid?>("SZKDevicesId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ShiftEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ShiftStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SystemRemarks")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TimeIn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("TimeOut")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<int?>("XCompany_BranchId")
                        .HasColumnType("integer");

                    b.HasKey("TimeLogId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SZKDevicesId");

                    b.HasIndex("XCompany_BranchId");

                    b.ToTable("EmployeeTimeLog");
                });

            modelBuilder.Entity("SCICHRPortal.Data.Entities.LeaveRequest", b =>
                {
                    b.Property<int>("LeaveRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LeaveRequestId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateRequest")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LeaveReason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("integer");

                    b.Property<double>("RequestDays")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("LeaveRequestId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("LeaveRequest");
                });

            modelBuilder.Entity("SCICHRPortal.Data.Entities.Metadatas.CutOff", b =>
                {
                    b.Property<int>("CutOffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CutOffId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("CutOffId");

                    b.ToTable("CutOff");
                });

            modelBuilder.Entity("SCICHRPortal.Data.Entities.Metadatas.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DeptCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("DepartmentId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("SCICHRPortal.Data.Entities.Metadatas.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Device");
                });

            modelBuilder.Entity("SCICHRPortal.Data.Entities.Metadatas.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Address")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("PositionId")
                        .HasColumnType("integer");

                    b.Property<string>("Suffix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PositionId");

                    b.HasIndex("UserId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("SCICHRPortal.Data.Entities.Metadatas.Holiday", b =>
                {
                    b.Property<int>("HolidayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HolidayId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("HolidayDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HolidayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("HolidayType")
                        .HasMaxLength(100)
                        .HasColumnType("integer");

                    b.Property<int>("HolidayTypes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("HolidayId");

                    b.ToTable("Holiday");
                });

            modelBuilder.Entity("SCICHRPortal.Data.Entities.Metadatas.LeaveType", b =>
                {
                    b.Property<int>("LeaveTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LeaveTypeId"));

                    b.Property<int>("AllowedDays")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<string>("LeaveDescription")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("LeaveTypeId");

                    b.ToTable("LeaveType");
                });

            modelBuilder.Entity("SCICHRPortal.Data.Entities.Metadatas.Module", b =>
                {
                    b.Property<int>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ModuleId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("ModuleId");

                    b.ToTable("Module");
                });

            modelBuilder.Entity("SCICHRPortal.Data.Entities.Metadatas.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PositionId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("PositionId");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("SCICHRPortal.Data.Entities.Metadatas.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("SCICHRPortal.Data.Entities.Metadatas.Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShiftId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("FridayShiftEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FridayShiftStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("MondayShiftEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("MondayShiftStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("NoLeaveAbsentCountLimit")
                        .HasColumnType("integer");

                    b.Property<int>("NoTimeLogCountLimit")
                        .HasColumnType("integer");

                    b.Property<string>("RestDays")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SaturdayShiftEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("SaturdayShiftStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ShiftLateMinuteGracePeriod")
                        .HasColumnType("integer");

                    b.Property<int>("ShiftLateTotalMinuteLimit")
                        .HasColumnType("integer");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("SundayShiftEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("SundayShiftStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ThursdayShiftEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ThursdayShiftStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("TuesdayShiftEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("TuesdayShiftStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("WednesdayShiftEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("WednesdayShiftStart")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ShiftId");

                    b.ToTable("Shift");
                });

            modelBuilder.Entity("SCICHRPortal.Data.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("RoleId");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedAt = new DateTime(2025, 4, 18, 10, 30, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "jun rivas",
                            Deleted = false,
                            Description = "Administrator",
                            Name = "Administrator"
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedAt = new DateTime(2025, 4, 18, 10, 30, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "jun rivas",
                            Deleted = false,
                            Description = "Other",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("SCICHRPortal.Data.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPasswordChanged")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<bool>("Locked")
                        .HasColumnType("boolean");

                    b.Property<int>("LoginAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Username")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("UserId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Active = false,
                            CreatedAt = new DateTime(2025, 4, 18, 10, 30, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "jun rivas",
                            Deleted = false,
                            Email = "superadmin@mail.com",
                            FirstName = "Super",
                            IsApproved = true,
                            IsPasswordChanged = false,
                            LastName = "Admin",
                            Locked = false,
                            LoginAttempts = 0,
                            Password = "4DRtkqzRrxUk9Px/+Zu7vzTIk5f0dHc4mPgicSMkQzI=",
                            Salt = "ml4A7caIeJit28zFyeiXVA==",
                            Username = "superadmin"
                        });
                });

            modelBuilder.Entity("SCICHRPortal.Data.Entities.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserRoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UserRoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            UserRoleId = 1,
                            CreatedAt = new DateTime(2025, 4, 18, 10, 30, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "jun rivas",
                            Deleted = false,
                            RoleId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("SCICHRPortal.Data.TimekeepingTables.SZKDevices", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("APIVersion")
                        .HasColumnType("text");

                    b.Property<int>("AntiPassback")
                        .HasColumnType("integer");

                    b.Property<bool>("AntiPassbackOn")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceFunction")
                        .HasColumnType("text");

                    b.Property<string>("DeviceInformation")
                        .HasColumnType("text");

                    b.Property<bool>("FaceSupported")
                        .HasColumnType("boolean");

                    b.Property<bool>("FingerprintSupported")
                        .HasColumnType("boolean");

                    b.Property<string>("FirmwareVersion")
                        .HasColumnType("text");

                    b.Property<string>("IPAddress")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyMapping")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LockOpenDuration")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool>("PalmSupported")
                        .HasColumnType("boolean");

                    b.Property<string>("RegistryCode")
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<string>("SyncStatus")
                        .HasColumnType("text");

                    b.Property<string>("TimeZone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ZKDevices");
                });

            modelBuilder.Entity("SCICHRPortal.Data.XscribeTables.XCompany_Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Addr_Area_Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Addr_City_Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Addr_Country_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Addr_Line1")
                        .HasColumnType("text");

                    b.Property<string>("Addr_Line2")
                        .HasColumnType("text");

                    b.Property<string>("Addr_Zip")
                        .HasColumnType("text");

                    b.Property<int?>("Authorized_Tax_Representative_Employee_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Authorized_Tax_Representative_Identification_Expiration_Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Authorized_Tax_Representative_Identification_Issuance_Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Authorized_Tax_Representative_Identification_Number")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Company_Branch_Code")
                        .HasColumnType("text");

                    b.Property<int>("Company_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Cost_Center")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Creation_Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool?>("Disabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Division")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Group")
                        .HasColumnType("text");

                    b.Property<string>("LandLine")
                        .HasColumnType("text");

                    b.Property<string>("Mobile")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Num_Employees")
                        .HasColumnType("integer");

                    b.Property<string>("Pagibig_Number")
                        .HasColumnType("text");

                    b.Property<string>("Philhealth_Number")
                        .HasColumnType("text");

                    b.Property<string>("Rdo_Code")
                        .HasColumnType("text");

                    b.Property<string>("Registered_Name")
                        .HasColumnType("text");

                    b.Property<string>("SSS_Number")
                        .HasColumnType("text");

                    b.Property<string>("Segment")
                        .HasColumnType("text");

                    b.Property<string>("Tin")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<bool?>("Vat")
                        .HasColumnType("boolean");

                    b.Property<double?>("Vat_Ratio")
                        .HasColumnType("double precision");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.Property<bool>("_Deleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("XCompany_Branch");
                });

            modelBuilder.Entity("SCICHRPortal.Data.XscribeTables.XCompany_Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int>("Company_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("XCompany_Position");
                });

            modelBuilder.Entity("SCICHRPortal.Data.XscribeTables.XDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Company_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool>("_Deleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("XDepartment");
                });

            modelBuilder.Entity("SCICHRPortal.Data.XscribeTables.XEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Birth_Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Birth_Place_City_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Blood_Type")
                        .HasColumnType("text");

                    b.Property<int?>("Business_Unit_Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Citizenship_Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Company_BranchId")
                        .HasColumnType("integer");

                    b.Property<int?>("Company_Branch_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Company_Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Company_Job_Class_Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Company_Job_Grade_Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Company_Job_Rank_Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Company_Location_Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Company_PositionId")
                        .HasColumnType("integer");

                    b.Property<int?>("Company_Position_Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Default_Hr_Payroll_Record_Id")
                        .HasColumnType("integer");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<int?>("Department_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Display_Name")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int?>("Employee_Classification_Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Employee_Group_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Employee_code")
                        .HasColumnType("text");

                    b.Property<string>("Employment_Status")
                        .HasColumnType("text");

                    b.Property<bool?>("Expat")
                        .HasColumnType("boolean");

                    b.Property<string>("First_Name")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<double?>("Height_M")
                        .HasColumnType("double precision");

                    b.Property<string>("LandLine")
                        .HasColumnType("text");

                    b.Property<string>("Last_Name")
                        .HasColumnType("text");

                    b.Property<string>("Location_Address_Line1")
                        .HasColumnType("text");

                    b.Property<string>("Location_Address_Line2")
                        .HasColumnType("text");

                    b.Property<int?>("Location_Address_Location_Area_Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Location_Address_Location_Building_Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Location_Address_Location_City_Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Location_Address_Location_Country_Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Location_Address_Location_Zone_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Location_Address_Zip")
                        .HasColumnType("text");

                    b.Property<string>("Marital_Status")
                        .HasColumnType("text");

                    b.Property<string>("Middle_Name")
                        .HasColumnType("text");

                    b.Property<string>("Mobile")
                        .HasColumnType("text");

                    b.Property<int?>("Nationality_Id")
                        .HasColumnType("integer");

                    b.Property<string>("NickName")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Num_201_Files")
                        .HasColumnType("integer");

                    b.Property<int?>("Num_Employments")
                        .HasColumnType("integer");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<int?>("Religion_Id")
                        .HasColumnType("integer");

                    b.Property<int?>("SubDepartment_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Suffix")
                        .HasColumnType("text");

                    b.Property<string>("Timekeeping_Device_Identifier")
                        .HasColumnType("text");

                    b.Property<double?>("Weight_Kg")
                        .HasColumnType("double precision");

                    b.Property<string>("X_Point_Of_Contact")
                        .HasColumnType("text");

                    b.Property<string>("X_Seat_Class")
                        .HasColumnType("text");

                    b.Property<bool>("_Deleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Company_BranchId");

                    b.HasIndex("Company_PositionId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("XEmployee");
                });

            modelBuilder.Entity("SCICHRPortal.Data.Entities.BiometricsLog", b =>
                {
                    b.HasOne("SCICHRPortal.Data.TimekeepingTables.SZKDevices", "SZKDevices")
                        .WithMany()
                        .HasForeignKey("SZKDevicesId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SCICHRPortal.Data.XscribeTables.XCompany_Branch", "XCompany_Branch")
                        .WithMany()
                        .HasForeignKey("XCompany_BranchId");

                    b.Navigation("SZKDevices");

                    b.Navigation("XCompany_Branch");
                });

            modelBuilder.Entity("SCICHRPortal.Data.Entities.EmployeeAttendance", b =>
                {
                    b.HasOne("SCICHRPortal.Data.XscribeTables.XCompany_Branch", "Company_Branch")
                        .WithMany()
                        .HasForeignKey("Company_BranchId");

                    b.HasOne("SCICHRPortal.Data.XscribeTables.XEmployee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SCICHRPortal.Data.Entities.EmployeeTimeLog", "EmployeeTimeLog")
                        .WithMany()
                        .HasForeignKey("TimeLogId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SCICHRPortal.Data.TimekeepingTables.SZKDevices", "ZKDevices")
                        .WithMany()
                        .HasForeignKey("ZKDevicesId");

                    b.Navigation("Company_Branch");

                    b.Navigation("Employee");

                    b.Navigation("EmployeeTimeLog");

                    b.Navigation("ZKDevices");
                });

            modelBuilder.Entity("SCICHRPortal.Data.Entities.EmployeeShift", b =>
                {
                    b.HasOne("SCICHRPortal.Data.XscribeTables.XCompany_Branch", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("SCICHRPortal.Data.TimekeepingTables.SZKDevices", "SZKDevices")
                        .WithMany()
                        .HasForeignKey("SZKDevicesId");

                    b.HasOne("SCICHRPortal.Data.Entities.Metadatas.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("SZKDevices");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("SCICHRPortal.Data.Entities.EmployeeShiftDevice", b =>
                {
                    b.HasOne("SCICHRPortal.Data.XscribeTables.XCompany_Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId");

                    b.HasOne("SCICHRPortal.Data.XscribeTables.XEmployee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SCICHRPortal.Data.TimekeepingTables.SZKDevices", "SZKDevices")
                        .WithMany()
                        .HasForeignKey("SZKDevicesId");

                    b.HasOne("SCICHRPortal.Data.Entities.Metadatas.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Employee");

                    b.Navigation("SZKDevices");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("SCICHRPortal.Data.Entities.EmployeeTimeLog", b =>
                {
                    b.HasOne("SCICHRPortal.Data.XscribeTables.XEmployee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SCICHRPortal.Data.TimekeepingTables.SZKDevices", "SZKDevices")
                        .WithMany()
                        .HasForeignKey("SZKDevicesId");

                    b.HasOne("SCICHRPortal.Data.XscribeTables.XCompany_Branch", "XCompany_Branch")
                        .WithMany()
                        .HasForeignKey("XCompany_BranchId");

                    b.Navigation("Employee");

                    b.Navigation("SZKDevices");

                    b.Navigation("XCompany_Branch");
                });

            modelBuilder.Entity("SCICHRPortal.Data.Entities.LeaveRequest", b =>
                {
                    b.HasOne("SCICHRPortal.Data.Entities.Metadatas.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SCICHRPortal.Data.Entities.Metadatas.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("SCICHRPortal.Data.Entities.Metadatas.Employee", b =>
                {
                    b.HasOne("SCICHRPortal.Data.Entities.Metadatas.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SCICHRPortal.Data.Entities.Metadatas.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SCICHRPortal.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Department");

                    b.Navigation("Position");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SCICHRPortal.Data.Entities.UserRole", b =>
                {
                    b.HasOne("SCICHRPortal.Data.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SCICHRPortal.Data.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SCICHRPortal.Data.XscribeTables.XEmployee", b =>
                {
                    b.HasOne("SCICHRPortal.Data.XscribeTables.XCompany_Branch", "Company_Branch")
                        .WithMany()
                        .HasForeignKey("Company_BranchId");

                    b.HasOne("SCICHRPortal.Data.XscribeTables.XCompany_Position", "Company_Position")
                        .WithMany()
                        .HasForeignKey("Company_PositionId");

                    b.HasOne("SCICHRPortal.Data.XscribeTables.XDepartment", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Company_Branch");

                    b.Navigation("Company_Position");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SCICHRPortal.Data.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
